---
linux: #Группа хостов 
  children: #Обозначение, что будет подгруппа хостов
    nginx: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm_1: #Имя машины
          ansible_host: 84.201.129.148 #Адрес машины
        vm_2:
          ansible_host: 84.201.134.253
        vm_3:
          ansible_host: 89.169.137.237

  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: "bohan"
    ansible_password: "qwerty"
    connection_protocol: ssh #тип подключения
    ansible_become: false #Становиться ли другим пользователем после подключения 
